name: GreenCart CI/CD Pipeline

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    name: Build & Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/GreenCart
            git fetch origin deployment
            git checkout deployment
            git reset --hard origin/deployment
            sudo docker compose down --remove-orphans
            sudo docker compose build --no-cache
            sudo docker compose up -d
